#!/usr/bin/env sh

set -e

BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
    echo "Push to $BRANCH prevented by pre-push hook. Use '--no-verify' to skip the pre-push hook"
    exit 1
fi
